### ISSUE TITLE
device_class and 'entity_id' depreciated

### ISSUE THREAD

**Issue by MechEng70** [nitobuendia/oura-custom-component#12]
Getting these warnings in core:

1. device_class

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.sleep_temperature_delta_yesterday (<class 'homeassistant.components.template.sensor.SensorTemplate'>) with device_class None reports a temperature in °C which will be converted to °F. Temperature conversion for entities without correct device_class is deprecated and will be removed from Home Assistant Core 2022.3. Please update your configuration if device_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

2. From the configuration.yaml file due to the sensor templates.  Documentation change on the Code page for sensors.

WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option near /config/configuration.yaml:302 is deprecated, please remove it from your configuration

**Comment by nitobuendia** [comment]
Hi @MechEng70 - `sensor.sleep_temperature_delta_yesterday` is not a sensor from this custom component directly.

I believe you're using the templates sensor that we recommend on the notes to make it accessible. You can see this on the error messate since it's coming from `homeassistant.components.template.sensor.SensorTemplate` (see `SensorTemplate` and not this custom component).

Do you have something like this somewhere in your `configuration.yaml` and/or derived files?

```yaml

    - name: "Sleep Temperature Delta Yesterday"
      entity_id: sleep_temperature_delta_yesterday
      unique_id: sleep_temperature_delta_yesterday
      unit_of_measurement: "°C"
      state: >
        {{ states.sensor.sleep_quality.attributes.yesterday.temperature_delta }}
      icon: "mdi:thermometer-lines"
```

I think what you'd need to do is:
1. Removing `entity_id` if you have one.
2. Adding `device_class: temperature`


However, for support for this sensor, I would encourage you to check the [Home-Assistant community](https://community.home-assistant.io/).
