### ISSUE TITLE
[Bug] 0d missing on sleep periods sensor

### ISSUE THREAD

**Issue by nitobuendia** [nitobuendia/oura-custom-component#27]
_Originally posted by @akeslo in https://github.com/nitobuendia/oura-custom-component/issues/10#issuecomment-1379645988_

### My Config
```
  - platform: oura
    access_token: XXXXREMOVEDXXXXX
    scan_interval: 7200
    sensors:
     sleep:
       name: oura_sleep_metrics
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 7d_ago 
     sleep_periods:
       name: oura_sleep_periods
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 7d_ago       
     sleep_score:
       name: oura_sleep_score
       max_backfill: 0 
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 7d_ago
```

### sleep_periods (oura_sleep)
* 0d is not an attribute despite it being in the config.

**Comment by nitobuendia** [comment]
I can reproduce this bug. In my case, 0d_ago works but 1d_ago data was missing and this is what I see on my `sleep_periods`

```yaml
0d_ago: 
- day: '2023-01-15'
  total_sleep_duration_in_hours: 6.07

2d_ago: 
- day: '2023-01-13'
  total_sleep_duration_in_hours: 5.95
```

1d_ago is missing because there was no data found. This has nothing to do with the `0d` but with the fact that there was no data for that given day and can affect any dates.
