### ISSUE TITLE
[Bug] Workouts sensor does not produce any data

### ISSUE THREAD

**Issue by nitobuendia** [nitobuendia/oura-custom-component#31]
I just temporarily renamed the sensor to oura_workouts2, same thing....

```
     workouts:
        name: oura_workouts2
        max_backfill: 0
        monitored_dates:
        - yesterday
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
```

![image](https://user-images.githubusercontent.com/3003773/215111184-17c4e1b7-1586-4729-bcbb-17ee803a4622.png)

_Originally posted by @akeslo in https://github.com/nitobuendia/oura-custom-component/issues/29#issuecomment-1406583778_
